const fileSystem = require('fs');
const utility = require('./utility');

/**
 * Saves generated files
 * @name saveGeneratedFiles
 * @description save files generated by the template engine
 * @param {Array of Objects} files
 *       Elements: {string} folder
 *                 {string} fullPath 
 *                 {string} fileName 
 */
function saveGeneratedFiles(files) {
    files.forEach(generatedFile => {
        if (!fileSystem.existsSync(generatedFile.folder)) {
            fileSystem.mkdirSync(generatedFile.folder);
        }

        fileSystem.writeFileSync(`${generatedFile.fullPath}`, generatedFile.content, function(err) {
            if(err) {
                return console.log(err);
            }
        }); 
    });
}

/**
 * Display generated files
 * @name displaySavedItems
 * @description display generated files from the given template that have been saved to disk
 * @param {Array of Objects} files
 *       Elements: {string} folder
 *                 {string} fullPath 
 *                 {string} fileName 
 */
function displaySavedFiles(files, templateName){
    console.log(`Template: ${templateName}, generated the following files:`);
    files.forEach(generatedFile => {
         console.log(`${utility.tab}--${generatedFile.fileName}`);
    });
}

module.exports = {saveGeneratedFiles, displaySavedFiles};